project:
  type: website
  output-dir: docs
  preview:
    watch-inputs: true
    browser: true

website:
  title: "Sam P"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Projects
      - href: about.qmd
        text: Connect
    right:
      - icon: github
        href: https://github.com/Pylon521/
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/samantha-p5221/
        target: _blank
        
format:
  html:
    theme: flatly
    css: styles.css
    output-dir: docs
    toc: true
    code-fold: true

execute:
# true to disable reruning
  cache: true
  echo: true
  warning: false
